version: '3.8'
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
      - n8n-data:/home/node/.n8n

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/creditdb

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  cloudflared:
    volumes:
      - ~/.cloudflared:/etc/cloudflared
    command: tunnel --config /etc/cloudflared/config.yml run

volumes:
  n8n-data:
  mongo-data:

